### ISSUE TITLE
Multiple Tech Contacts for NIR query

### ISSUE THREAD

**Issue by kwheeles** [secynic/ipwhois#172] opened 2017-05-24 13:45 UTC
python: 3.6.1, ipwhois version 0.15.1
Problem: IPWhois('131.113.0.0')  yields error shown below.  A log is included below that, showing that the 'contact' level query (nir._get_contact()) is being invoked with multiple contact keys.
I am new to ipwhois, but it appears to me the NIR code is set up to handle a single entry for both the technical and administrative contacts, but that sometimes there may be more than one.  I think the fix is in nir.lookup().  My guess for location of code to change is at bottom:

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/keith/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-114368cbafb5>", line 1, in <module>
    a=IPWhois('131.113.0.0').lookup()
  File "/home/keith/anaconda3/lib/python3.5/site-packages/ipwhois/ipwhois.py", line 81, in lookup
    return self.lookup_whois(*args, **kwargs)
  File "/home/keith/anaconda3/lib/python3.5/site-packages/ipwhois/ipwhois.py", line 187, in lookup_whois
    field_list=nir_field_list, is_offline=False
  File "/home/keith/anaconda3/lib/python3.5/site-packages/ipwhois/nir.py", line 592, in lookup
    dt_format=dt_format
  File "/home/keith/anaconda3/lib/python3.5/site-packages/ipwhois/nir.py", line 424, in _get_contact
    request_type=NIR_WHOIS[nir]['request_type']
  File "/home/keith/anaconda3/lib/python3.5/site-packages/ipwhois/net.py", line 884, in get_http_raw
    raise HTTPLookupError('HTTP lookup failed for {0}.'.format(url))
ipwhois.exceptions.HTTPLookupError: HTTP lookup failed for http://whois.nic.ad.jp/cgi-bin/whois_gw?lang=%2Fe&key=TH985JP
SH567JP
TY11794JP
TO13574JP&submit=query.

Log output from run with logging:

2017-05-24 08:33:52,644 ASN lookup for 131.113.0.0
2017-05-24 08:33:52,644 ASN query for 0.0.113.131.origin.asn.cymru.com
2017-05-24 08:33:52,691 RDAP lookup for 131.113.0.0
2017-05-24 08:33:52,692 Response not given, perform RDAP lookup for http://rdap.apnic.net/ip/131.113.0.0
2017-05-24 08:33:52,692 HTTP query for 131.113.0.0 at http://rdap.apnic.net/ip/131.113.0.0
2017-05-24 08:33:53,551 Parsing RDAP network object
2017-05-24 08:33:53,551 Parsing RDAP root level entities
2017-05-24 08:33:53,552 Response not given, perform WHOIS lookup for 131.113.0.0
2017-05-24 08:33:53,553 HTTP query for 131.113.0.0 at http://whois.nic.ad.jp/cgi-bin/whois_gw?lang=%2Fe&key=131.113.0.0&submit=query
2017-05-24 08:34:00,087 Parsing NIR WHOIS data
2017-05-24 08:34:00,087 NIR whois field parsing failed for created: time data '' does not match format '%Y/%m/%d %H:%M:%S(JST)'
2017-05-24 08:34:00,088 HTTP query for 131.113.0.0 at http://whois.nic.ad.jp/cgi-bin/whois_gw?lang=%2Fe&key=JP00034742&submit=query
2017-05-24 08:34:00,698 HTTP query for 131.113.0.0 at http://whois.nic.ad.jp/cgi-bin**/whois_gw?lang=%2Fe&key=TH985JP
SH567JP
TY11794JP
TO13574JP&submit=query**

            contacts = {
                'admin': temp_net['contact_admin'],
                'tech': temp_net['contact_tech']
            }

            del (
                temp_net['contact_admin'],
                temp_net['contact_tech']
            )

            if not is_offline:

                for key, val in contacts.items():

                    if len(val) > 0:

                        if isinstance(val, str):                       ** if not, maybe?  or are they delimited in some way? **

                            val = [val]

**Comment by kwheeles** [comment] 2017-05-26 12:40
Proposed fix:
Following code segment above:
            del (
                temp_net['contact_admin'],
                temp_net['contact_tech']
            )

            if not is_offline:

                for key, val in contacts.items():

                    if len(val) > 0:

                        if isinstance(val, str):
                            
                            **if '\n' in val:
                                
                                val = val.split('\n')
                                
                            else:

                                val = [val]**

                        for contact in val:

                            if contact in global_contacts.keys():

                                temp_net['contacts'][key] = (
                                    global_contacts[contact]

**Comment by kwheeles** [comment] 2017-05-26 14:48
Have now tested this via monkey-patch, it solves the problem at 131.113.0.0.
Simpler code is:

if len(val) > 0:
    if isinstance(val, str):
        val = val.splitlines()
for contact in val:

**Comment by secynic** [comment] 2017-05-27 00:27
Thanks, I will take a look this weekend.

**Comment by secynic** [comment] 2017-05-30 03:13
Nice catch, just confirmed the same error. 

Let me know if you want to submit a pull request (to dev please, not master), and I will run some broader tests. This also gives me an excuse to expand the test IP lists.

**Comment by kwheeles** [comment] 2017-05-30 09:37
To be very honest I don't know much about git or doing a pull request.  So I believe the answer is no (although I'd sure like to get this fixed in the production version)..

I have encountered this error several times, just used a sample failure to trace the issue and verified correction on it using a monkey-patch.

On 05/29/2017 11:13 PM, Philip Hane wrote:

Nice catch, just confirmed the same error.

Let me know if you want to submit a pull request (to dev please, not master), and I will run some broader tests. This also gives me an excuse to expand the test IP lists.

**Comment by secynic** [comment] 2017-05-31 02:11
No worries. Seeing as this is the only current open bug, and dev is able to merge, I will treat this as the top priority. PyPI release will be delayed until 1.0.0 is ready, of course.

I appreciate it if you can provide any other IPs (in different subnets) that you are experiencing this error with.

**Comment by kwheeles** [comment] 2017-05-31 10:20
Here are some other IPs that fail:


160.12.0.0

192.0.2.0

165.14.0.0

147.157.0.0

158.217.0.0

198.97.38.0

130.69.0.0

130.54.0.0

On 05/30/2017 10:11 PM, Philip Hane wrote:

No worries. Seeing as this is the only current open bug, and dev is able to merge, I will treat this as the top priority. PyPI release will be delayed until 1.0.0 is ready, of course.

I appreciate it if you can provide any other IPs (in different subnets) that you are experiencing this error with.

**Comment by secynic** [comment] 2017-06-10 22:30
Fixed, waiting on tests to merge.

192.0.2.0 failed since it is defined as TEST-NET-1 via RFC 5737
198.97.38.0 failed since it is showing as IANA Reserved. I opened #174 for that.

**Comment by secynic** [comment] 2017-06-10 23:57
Merged in #175

**Closed by secynic** 2017-06-10 23:57 UTC
Labels: bug

**Comment by kwheeles** [comment] 2017-06-11 01:22
Thank you!
