### ISSUE TITLE
PIP install fails

### ISSUE THREAD

**Issue by lllama** [secynic/ipwhois#55] opened 2015-02-02 14:07 UTC
Looks like there is an encoding issue with CHANGES.rst:

```
Downloading/unpacking ipwhois (from -r requirements.txt (line 2))
  Downloading ipwhois-0.9.1.zip
  Running setup.py (path:/tmp/pip_build_root/ipwhois/setup.py) egg_info for package ipwhois
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/ipwhois/setup.py", line 31, in <module>
        open('CHANGES.rst').read()])
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1435: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/ipwhois/setup.py", line 31, in <module>

    open('CHANGES.rst').read()])

  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1435: ordinal not in range(128)

```

This is with python 3.4 on ubuntu

**Comment by secynic** [comment] 2015-02-03 00:59
Strange.... I am not able to reproduce the issue. I believe it is triggering on "Fixed some type errors: Expected type 'str', got 'dict[str, dict]' instead."

The .rst files are UTF-8, and it is trying to decode ascii. I'm going to change setup.py to use the built-in codecs module, and have you test. Should have something pushed to dev shortly.

**Comment by secynic** [comment] 2015-02-03 01:59
Please test install the dev branch. 

Fixed in d289a416a2f56eaae16c6bd7987e180ee451280b

**Comment by lllama** [comment] 2015-02-03 08:42
Excellent! Seems to be working now:
```
# pip3  install -r requirements.txt
Downloading/unpacking git+https://github.com/secynic/ipwhois.git@dev (from -r requirements.txt (line 1))
  Cloning https://github.com/secynic/ipwhois.git (to dev) to /tmp/pip-l6l1z61l-build
  Running setup.py (path:/tmp/pip-l6l1z61l-build/setup.py) egg_info for package from git+https://github.com/secynic/ipwhois.git@dev

Downloading/unpacking dnspython3 (from ipwhois==0.9.2->-r requirements.txt (line 1))
  Downloading dnspython3-1.12.0.zip (226kB): 226kB downloaded
  Running setup.py (path:/tmp/pip_build_root/dnspython3/setup.py) egg_info for package dnspython3

Installing collected packages: dnspython3, ipwhois
  Running setup.py install for dnspython3

  Running setup.py install for ipwhois

Successfully installed dnspython3 ipwhois
Cleaning up...
```

**Comment by secynic** [comment] 2015-02-04 04:06
Great, thanks.

**Closed by secynic** 2015-02-04 04:06 UTC
Labels: bug
