### ISSUE TITLE
crash on korean hostnames: ssl.CertificateError: hostname 

### ISSUE THREAD

**Issue by shakaran** [secynic/ipwhois#255] opened 2020-04-09 00:23 UTC
```
Traceback (most recent call last):
  File "/root/src/ipwhois/ipwhois/net.py", line 874, in get_http_raw
    data = self.opener.open(conn, timeout=self.timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib64/python3.6/http/client.py", line 1415, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 650, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 287, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname '후이즈검색.한국' doesn't match either of 'whois.kisa.or.kr', 'xn--c79as89aj0e29b77z.xn--3e0b707e', 'whois.kr', 'xn--c79as89aj0e29b77z.kr', 'whois.nic.or.kr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ipwhois_cli.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/root/src/ipwhois/ipwhois/scripts/ipwhois_cli.py", line 1481, in <module>
    get_asn_description=(not script_args.skip_asn_description)
  File "/root/src/ipwhois/ipwhois/scripts/ipwhois_cli.py", line 1028, in lookup_rdap
    ret = self.obj.lookup_rdap(**kwargs)
  File "/root/src/ipwhois/ipwhois/ipwhois.py", line 327, in lookup_rdap
    field_list=nir_field_list, is_offline=False
  File "/root/src/ipwhois/ipwhois/nir.py", line 538, in lookup
    form_data=form_data
  File "/root/src/ipwhois/ipwhois/net.py", line 907, in get_http_raw
    raise HTTPLookupError('HTTP lookup failed for {0}.'.format(url))
ipwhois.exceptions.HTTPLookupError: HTTP lookup failed for https://xn--c79as89aj0e29b77z.xn--3e0b707e/eng/whois.jsc.
```

**Comment by secynic** [comment] 2020-09-01 21:01
Please try the dev branch. Duplicate of #207

**Closed by secynic** 2020-09-01 21:01 UTC
Labels: duplicate, gathering information
